name = "HCL"
grammar = "hcl"
pathSuffixes = ["hcl", "tf", "tfvars", "tfstate"]
lineComments = ["# "]
autoCloseBefore = ";:.,=}])>` \n\t\""
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = false },
]
